export const todosTypes = {
  ADD_NEW_TODO: "ADD_NEW_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  EDIT_TODO: "EDIT_TODO",
  REMOVE_ALL_TODOS: "REMOVE_ALL_TODOS",
  CHANGE_TODO_STATE: "CHANGE_TODO_STATE",
  CHANGE_TODOS_TYPE: "CHANGE_TODOS_TYPE",
  CHANGE_TO_UNCOMPLETE: "CHANGE_TO_UNCOMPLETE",
  CHANGE_TO_COMPLETE: "CHANGE_TO_COMPLETE",
};
